# Generated by Django 3.2.16 on 2023-08-12 00:40

import community.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=128, unique=True)),
                ('name_en', models.CharField(max_length=128, unique=True)),
                ('url_id', models.CharField(blank=True, default=None, max_length=32, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_links', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=community.models.Community.get_logo_path)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=community.models.Community.get_banner_path)),
                ('is_publicly_visible', models.BooleanField(default=False)),
                ('is_accepting_requests', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('community_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='community.community')),
                ('room', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('is_official', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('R', 'Recruiting'), ('C', 'Closed'), ('D', 'Disbanded')], default='R', max_length=1)),
            ],
            bases=('community.community',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('community_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='community.community')),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            bases=('community.community',),
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('community_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='community.community')),
                ('room', models.CharField(blank=True, max_length=32, null=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('R', 'Recruiting'), ('C', 'Closed'), ('D', 'Disbanded')], default='R', max_length=1)),
            ],
            bases=('community.community',),
        ),
    ]
